---
- name: check if zabbix_repo is installed
  command: dpkg-query -W zabbix_repo
  register: zabbix_repo_check_deb
  failed_when: zabbix_repo_check_deb.rc > 1
  changed_when: zabbix_repo_check_deb.rc == 1

- name: wget zabbix_repo
  get_url:
    url: "https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-4+debian11_all.deb"
    dest: "/media/zabbix_repo.deb"
    force: true
  when: zabbix_repo_check_deb.rc == 1

- name: install zabbix_repo
  apt:
    deb: "/media/zabbix_repo.deb"
  when: zabbix_repo_check_deb.rc == 1

- name: install zabbix packages
  apt:
    update_cache: true
    name:
      - "zabbix-agent2"
      - "zabbix-agent2-plugin-*"
    state: present
  notify: restart zabbix-agent2

- name: copy zabbix_agent2.conf
  copy:
    src: zabbix_agent2.conf
    dest: /etc/zabbix/zabbix_agent2.conf
  notify:
    - restart zabbix-agent2

