---
- name: install nginx
  hosts: web-servers
  become: yes
  
  roles:
    - role: geerlingguy.nginx

- name: setting up nginx
  hosts: web-servers
  become: yes

  tasks:
  - name: copy index
    template:
      src: ./nginx/index.html.j2
      dest: /var/www/index.html
    notify:
    - restart nginx

  - name: copy web.conf
    template:
      src: ./nginx/web.conf.j2
      dest: /etc/nginx/conf.d/web.conf
    notify: restart nginx

  - name: copy stub_status.conf
    copy:
      src: ./nginx/stub_status.conf
      dest: /etc/nginx/conf.d/
    notify: restart nginx

  - name: copy nginx.conf
    copy:
      src: ./nginx/nginx.conf
      dest: /etc/nginx/
    notify: restart nginx

  - name: start nginx
    service: name=nginx state=started

  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted
