---
- name: install zabbix-agent2
  hosts: all
  become: yes

  roles: 
    - role: zabbix_agent2

- name: test vm-1
  hosts: zabbix
  become: yes
  
  tasks:
    
    - name: Set credentials to access Zabbix Server API
      set_fact:
        ansible_user: Admin
        ansible_httpapi_pass: zabbix

    - name: add zabbix_server to zabbix
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 80
        ansible_httpapi_use_ssl: false
        ansible_httpapi_validate_certs: false
        ansible_zabbix_url_path: ""
        ansible_host: "{{ zabbix_server_ip }}"
      become: false
      community.zabbix.zabbix_host:
        host_name: Zabbix server
        visible_name: Zabbix server
        host_groups:
          - Linux servers
        link_templates:
          - Linux by Zabbix agent
          - Zabbix server health
        status: enabled
        state: present
        inventory_mode: automatic
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "127.0.0.1"
            dns: ""
            port: "10050"

    - name: add vm-1 to zabbix
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 80
        ansible_httpapi_use_ssl: false
        ansible_httpapi_validate_certs: false
        ansible_zabbix_url_path: ""
        ansible_host: "{{ zabbix_server_ip }}"
      become: false
      community.zabbix.zabbix_host:
        host_name: vm-1
        visible_name: vm-1
        host_groups:
          - Linux servers
        link_templates:
          - Linux by Zabbix agent
          - Nginx by Zabbix agent
        status: enabled
        state: present
        inventory_mode: automatic
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ vm_1_ip }}"
            dns: ""
            port: "10050"
    
    - name: add vm-2 to zabbix
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 80
        ansible_httpapi_use_ssl: false
        ansible_httpapi_validate_certs: false
        ansible_zabbix_url_path: ""
        ansible_host: "{{ zabbix_server_ip }}"
      become: false
      community.zabbix.zabbix_host:
        host_name: vm-2
        visible_name: vm-2
        host_groups:
          - Linux servers
        link_templates:
          - Linux by Zabbix agent
          - Nginx by Zabbix agent
        status: enabled
        state: present
        inventory_mode: automatic
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ vm_2_ip }}"
            dns: ""
            port: "10050"

    - name: add elasticsearch to zabbix
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 80
        ansible_httpapi_use_ssl: false
        ansible_httpapi_validate_certs: false
        ansible_zabbix_url_path: ""
        ansible_host: "{{ zabbix_server_ip }}"
      become: false
      community.zabbix.zabbix_host:
        host_name: elasticsearch
        visible_name: elasticsearch
        host_groups:
          - Linux servers
        link_templates:
          - Linux by Zabbix agent
        status: enabled
        state: present
        inventory_mode: automatic
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ elastic_ip }}"
            dns: ""
            port: "10050"

    - name: add kibana to zabbix
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 80
        ansible_httpapi_use_ssl: false
        ansible_httpapi_validate_certs: false
        ansible_zabbix_url_path: ""
        ansible_host: "{{ zabbix_server_ip }}"
      become: false
      community.zabbix.zabbix_host:
        host_name: kibana
        visible_name: kibana
        host_groups:
          - Linux servers
        link_templates:
          - Linux by Zabbix agent
        status: enabled
        state: present
        inventory_mode: automatic
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ kibana_ip }}"
            dns: ""
            port: "10050"

    - name: add bastion to zabbix
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 80
        ansible_httpapi_use_ssl: false
        ansible_httpapi_validate_certs: false
        ansible_zabbix_url_path: ""
        ansible_host: "{{ zabbix_server_ip }}"
      become: false
      community.zabbix.zabbix_host:
        host_name: bastion
        visible_name: bastion
        host_groups:
          - Linux servers
        link_templates:
          - Linux by Zabbix agent
        status: enabled
        state: present
        inventory_mode: disabled
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ bastion_ip }}"
            dns: ""
            port: "10050"
