---
- name: install postgresql
  hosts: zabbix
  become: yes
  
  roles: 
    - role: psql

- name: install zabbix-server
  hosts: zabbix
  become: yes
  vars:
    password: 12345678
    db_password_hash: 25d55ad283aa400af464c76d713c07ad
 
  roles:
    - role: geerlingguy.apache
    - role: geerlingguy.php
    - role: community.zabbix.zabbix_server
      vars:
        zabbix_server_database: pgsql
        zabbix_server_database_long: postgresql
        zabbix_server_dbport: 5432
        zabbix_server_dbpassword: "{{ db_password_hash }}"
    - role: community.zabbix.zabbix_web
      vars:
        zabbix_api_server_url: "{{ zabbix_server_ip }}"
        zabbix_server_database: pgsql
        zabbix_db_type_long: postgresql
        zabbix_server_dbport: 5432
        zabbix_server_dbpassword: "{{ db_password_hash }}"
